### ISSUE TITLE
How to retrieve uport user profile data?

### ISSUE THREAD

**Issue by miguelmota** [ConsenSys/uport-lib#57]
`persona.profile` returns an address and it's not clear what to do next. I'd like to know how to retrieve uport account attributes such as name and profile image.

**Comment by christianlundkvist** [comment]
Hi @miguelmota, this was a bug in `uport-registry` and should now be fixed. Please try again, and thanks for the bug reports!

**Comment by miguelmota** [comment]
Thanks!
